// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfkONWkSU4Um95FTqc1b-uDuTwB2LFYkM',
    appId: '1:503379766778:web:28a755cdc794845952c843',
    messagingSenderId: '503379766778',
    projectId: 'lactgo-58ac3',
    authDomain: 'lactgo-58ac3.firebaseapp.com',
    storageBucket: 'lactgo-58ac3.appspot.com',
    measurementId: 'G-BJS4LQ6Z4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4MrQwI66AVp8htsZszcUp7O2jNCke0pE',
    appId: '1:503379766778:android:e2da7e58602e09dc52c843',
    messagingSenderId: '503379766778',
    projectId: 'lactgo-58ac3',
    storageBucket: 'lactgo-58ac3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL5p-E20PeMHygRJwySG8c6mdlReGoJIY',
    appId: '1:503379766778:ios:4d16116b6864bd8852c843',
    messagingSenderId: '503379766778',
    projectId: 'lactgo-58ac3',
    storageBucket: 'lactgo-58ac3.appspot.com',
    iosBundleId: 'com.example.lactgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL5p-E20PeMHygRJwySG8c6mdlReGoJIY',
    appId: '1:503379766778:ios:736262a8f5536a6652c843',
    messagingSenderId: '503379766778',
    projectId: 'lactgo-58ac3',
    storageBucket: 'lactgo-58ac3.appspot.com',
    iosBundleId: 'com.example.lactgo.RunnerTests',
  );
}
